### ISSUE TITLE
Configuration chloé

### ISSUE THREAD

**Issue by mpw-user** [datalab-mi/ridoc#38]
Traceback (most recent call last):
File "/usr/local/bin/docker-compose", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 67, in main
command()
File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 123, in perform_command
project = project_from_options('.', options)
File "/usr/local/lib/python3.6/dist-packages/compose/cli/command.py", line 69, in project_from_options
environment_file=environment_file
File "/usr/local/lib/python3.6/dist-packages/compose/cli/command.py", line 132, in get_project
verbose=verbose, version=api_version, context=context, environment=environment
File "/usr/local/lib/python3.6/dist-packages/compose/cli/docker_client.py", line 43, in get_client
environment=environment, tls_version=get_tls_version(environment)
File "/usr/local/lib/python3.6/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
client = APIClient(**kwargs)
File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 197, in __init__
self._version = self._retrieve_server_version()
File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 222, in _retrieve_server_version
'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Makefile:96: recipe for target 'elasticsearch' failed
make: *** [elasticsearch] Error 1

**Comment by victorjourne** [comment]
```
sudo groupadd docker
sudo usermod -aG docker $USER
```

**Comment by mpw-user** [comment]
problem fixed
